name: Deploy to staging environment

on:
  push:
    branches: [ stage ]

jobs:
  deploy:
    name: Build and Deploy project
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Gcloud Account
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT}}

      - name: Build container
        run: docker build . -t $IMAGE_NAME

      - name: Push docker image
        run: docker push $IMAGE_NAME

      - name: Deploy to cloud run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: ${{ IMAGE_NAME }}
          service: ${{ secrets.GCP_SERVICE_NAME }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: europe-west1