name: Deploy to staging environment

on:
  push:
    branches: [ stage ]

jobs:
  deploy:
    name: Build and Deploy project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: set environment variables
        run: |
          cat ./.github/variables.env >> $GITHUB_ENV

      - id: auth
        name: Authenticate to Gcloud Account
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT}}

      - name: Configure Docker
        run: gcloud auth configure-docker $ARTIFACT_REGISTRY_BASE_URL

      - name: Build container
        run: docker build . -t $ARTIFACT_REGISTRY_BASE_URL/$IMAGE_NAME:$IMAGE_TAG

      - name: Push docker image
        run: docker push $ARTIFACT_REGISTRY_BASE_URL/$IMAGE_NAME:$IMAGE_TAG

      - name: Deploy docker image to cloud run
        run: gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} --image $ARTIFACT_REGISTRY_BASE_URL/$IMAGE_NAME:$IMAGE_TAG --quiet --platform managed --region ${{secrets.GCP_REGION}} --project ${{ secrets.GCP_PROJECT_ID }}